=== R3tr086X/HTML/2º Trimestre/XSD/Ejercicio 6/lista.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="listaclientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cliente" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cif" type="cifType"/>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="diasentrega" type="xs:unsignedInt" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    <xs:simpleType name="cifType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{7}[0-9A-Z]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== R3tr086X/HTML/2º Trimestre/XSD/Ejercicio 6/lista.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaclientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="lista.xsd">
  <cliente>
    <cif>1234567F</cif>
    <nombre>Pepe</nombre>
    <diasentrega>23</diasentrega>
  </cliente>
  <cliente>
     <cif>2312122K</cif>
    <nombre>Alberto</nombre>
  </cliente>
</listaclientes>
