=== R3tr086X/HTML/2º Trimestre/Tarea Final 2ºTrimestre - LM/xsd_validación.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="historia">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="continente" type="continenteType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="ejemplo_cdata" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
    <xs:complexType name="continente">
      <xs:sequence>
        <xs:choice>
         <xs:element name="superficie">
           <xs:complexType>
              <xs:attribute name="actual" type="xs:string"/>
            </xs:complexType>
          </xs:element>
           <xs:element name="poblacion">
             <xs:complexType>
                <xs:attribute name="actual" type="xs:string"/>
             </xs:complexType>
            </xs:element>
        </xs:choice>
        <xs:element name="pais" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  
  <xs:complexType name="pais">
    <xs:sequence>
      <xs:element name="superficie" type="xs:string"/>
      <xs:element name="informacion" type="xs:string"/>
    </xs:sequence>
        <xs:attribute name="localizacion" type="localizacionType"/>
  </xs:complexType>
  
  <xs:complexType name="informacion">
    <xs:sequence>
      <xs:element name="nombre" type="nombreType"/>
      <xs:element name="formacion" type="formacionType"/>
      <xs:element name="hecho" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="imperio" type="imperioType"/>
      <xs:element name="sistema_gobierno_actual" type="xs:string"/>
      <xs:element name="moneda" type="xs:string" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>  
  </xs:complexType>
  
  <xs:complexType name="continenteType">
    <xs:sequence>
        <xs:attribute name="valor" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  
   <xs:simpleType name="localizacionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Norte"/>
      <xs:enumeration value="Sur"/>
      <xs:enumeration value="Este"/>
      <xs:enumeration value="Oeste"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="imperioType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SI"/>
      <xs:enumeration value="No"/>
    </xs:restriction>
  </xs:simpleType>
  
   <xs:complexType name="nombreType">
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="codigo">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="[a-zA-Z]{2}[1-9][0-9]"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType type="añoType">
      <xs:attribute name="año">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4}(aC|dC)"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  
</xs:schema>

=== R3tr086X/HTML/2º Trimestre/Tarea Final 2ºTrimestre - LM/xsd_datosHistoria.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="CSS_Historia.css"?>
<historia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="xsd_validación.xsd">
    <continente valor="Europa">
      <pais localizacion="Occidente">
        <superficie actual="505,990 km²"/>
        <informacion>
                <nombre codigo="eu33">España</nombre>
                <formacion año="1492dC"/>
                <hecho>Final de la Reconquista</hecho>
                <hecho>Unión dinástica de las coronas de Castilla y Aragón</hecho>
                <imperio>SI</imperio>
                <sistema_gobierno_actual>Monarquía parlamentaria</sistema_gobierno_actual>
                <moneda>Euro (€)</moneda>
        </informacion>
      </pais>
      
      <pais localizacion="Sur">
        <poblacion actual="60,317,116"/>
          <informacion>
                  <nombre codigo="eu45">Italia</nombre>
                  <formacion año="1861dC"/>
                  <hecho>Unificación nacional Italiana</hecho>
                  <imperio>SI</imperio>
                  <sistema_gobierno_actual>República parlamentaria</sistema_gobierno_actual>
                  <moneda>Euro (€)</moneda>
          </informacion>
      </pais>
    </continente>
    
    <continente valor="Africa">
      <pais localizacion="Norte">
        <superficie actual="1,010,407 km²"/>
        <informacion>
                <nombre codigo="af64">Egipto</nombre>
                <formacion año="3200aC"/>
                <hecho>Unificación de ciuades del Nilo</hecho>
                <imperio>SI</imperio>
                <sistema_gobierno_actual>República semipresidencialista</sistema_gobierno_actual>
                <moneda>Libra egipcia (EGP)</moneda>
        </informacion>
      </pais>
    </continente>
    
    <continente valor="&quot;America&quot;">
      <pais localizacion="Sur">
        <poblacion actual="19,458,310"/>
        <informacion>
                <nombre codigo="am54">Chile</nombre>
                <formacion año="1818dC"/>
                <hecho>Independencia de España</hecho>
                <imperio>NO</imperio>
                <sistema_gobierno_actual>República presidencialista</sistema_gobierno_actual>
        </informacion>
      </pais>
    </continente>
    
    <continente valor="&quot;Asia&quot;">
      <pais localizacion="Oriente">
        <superficie actual="377,975 km²"/>
        <informacion>
                <nombre codigo="as66">Japón</nombre>
                <formacion año="1868dC"/>
                <hecho>Restauración Meiji</hecho>
                <imperio>SI</imperio>
                <sistema_gobierno_actual>Monarquía constitucional</sistema_gobierno_actual>
                <moneda>Yen (¥)</moneda>
        </informacion>
      </pais>
    </continente>
    
    
    <ejemplo_cdata>
    <![CDATA[
        <p>Información HTML en un documento XML</p>
        <ul>
            <li>Elemento de lista 1</li>
            <li>Elemento de lista 2</li>
            <li>Elemento de lista 3</li>
        </ul>
    ]]>
    </ejemplo_cdata>
</historia>
